### ISSUE TITLE
Activating the microphone button restarts HomeAssistant

### ISSUE THREAD

**Issue by jramirezcolombia** [AlexxIT/StreamAssist#64]
When I activate the microphone from the button, Home Assistant loses connection and restarts. What is the cause and how can I fix it?

**Comment by RaylightGames** [comment]
i have same issue after upgrading HomeAssistant from 2025.1.1 to 2025.4.0

**Comment by xfaustus** [comment]
I have same issue after upgrading HomeAssistant from 2025.1.1 to 2025.4.0.
Additionally i don't see any error in the HA log

**Comment by jramirezcolombia** [comment]
I'm using version 2025.4.0 and nothing appears in the logs or in the debugging status either.

**Comment by kgroshert** [comment]
Upgrading HA from 2025.3 to 2025.4.0 ends with an out of memory error (OOM killer) and a rollback to 2025.3. After I disabled all integrations step by step I found this one to be the culprit.

Pls let me know if I can help debug. The OOM logs from the host don't help much as it just kills the main ha-core process.

**Comment by HomeStudiosDIY** [comment]
I just wanted to log this also as I have the same problem after upgrading to 2025.4 cannot seem to get log's and Home Assistant just reboots when you activate the MIC in Home Assistant

**Comment by Mariuss811** [comment]
Same Issue. Currently, on 2025.4.0 but had this issue before with 2024.3.X when I didn't set an "STT Start Media".
This seems to be something else. 

This error goes on forever till, I assume, the memory runs out:

```[custom_components.stream_assist.core] 
run_assist error <class 'TypeError'>: PipelineInput.__init__() got an unexpected keyword argument 'conversation_id'
```


Here is the full log as soon as I turn on the Microphone:

```
2025-04-03 12:10:09.729 DEBUG (MainThread) [homeassistant.core] 
Bus:Handling <Event call_service[L]: domain=switch, service=turn_on, service_data=entity_id=switch.wohnzimmer_micro_mic>

2025-04-03 12:10:09.729 DEBUG (MainThread) [homeassistant.core] 
Bus:Handling <Event state_changed[L]: entity_id=switch.wohnzimmer_micro_mic, 
old_state=<state switch.wohnzimmer_micro_mic=off; icon=mdi:numeric-0, 
friendly_name=Wohnzimmer Micro MIC @ 2025-04-03T12:10:00.867201+02:00>, 
new_state=<state switch.wohnzimmer_micro_mic=on; icon=mdi:numeric-0, 
friendly_name=Wohnzimmer Micro MIC @ 2025-04-03T12:10:09.729576+02:00>>

2025-04-03 12:10:09.730 DEBUG (MainThread) [custom_components.stream_assist.core.stream] 
stream open

2025-04-03 12:10:09.732 DEBUG (Recorder) [homeassistant.components.recorder.core] 
Processing task: <Event call_service[L]: domain=switch, service=turn_on, service_data=entity_id=switch.wohnzimmer_micro_mic>

2025-04-03 12:10:09.735 DEBUG (Recorder) [homeassistant.components.recorder.core] 
Processing task: <Event state_changed[L]: entity_id=switch.wohnzimmer_micro_mic, 
old_state=<state switch.wohnzimmer_micro_mic=off; icon=mdi:numeric-0, 
friendly_name=Wohnzimmer Micro MIC @ 2025-04-03T12:10:00.867201+02:00>, 
new_state=<state switch.wohnzimmer_micro_mic=on; icon=mdi:numeric-0, 
friendly_name=Wohnzimmer Micro MIC @ 2025-04-03T12:10:09.729576+02:00>>

2025-04-03 12:10:09.736 DEBUG (MainThread) [libav.tcp] 
Starting connection attempt to 192.168.178.164 port 554

2025-04-03 12:10:09.748 DEBUG (MainThread) [libav.tcp] 
Successfully connected to 192.168.178.164 port 554

2025-04-03 12:10:09.796 DEBUG (MainThread) [libav.rtsp] 
SDP:
v=0
o=- 1743672567143662 1 IN IP4 192.168.178.164
s=Session streamed by "preview"
i=reolink rtsp stream
t=0 0
a=tool:BC Streaming Media v202210012022.10.01
a=type:broadcast
a=control:*
a=range:npt=now-
a=x-qt-text-nam:Session streamed by "preview"
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:8192
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKCgPZA=,aO48sA==
a=recvonly
a=control:track1
m=audio 0 RTP/AVP 97
c=IN IP4 0.0.0.0
b=AS:8192
a=rtpmap:97 MPEG4-GENERIC/16000
a=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408
a=recvonly
a=control:track2

2025-04-03 12:10:09.845 DEBUG (MainThread) [libav.rtsp] 
setting jitter buffer size to 0

2025-04-03 12:10:13.674 DEBUG (MainThread) [homeassistant.components.assist_pipeline.audio_enhancer] 
Initialized microVAD

2025-04-03 12:10:13.674 DEBUG (MainThread) [custom_components.stream_assist.core] 
run_assist error <class 'TypeError'>: PipelineInput.__init__() got an unexpected keyword argument 'conversation_id'

2025-04-03 12:10:13.675 DEBUG (MainThread) [homeassistant.components.assist_pipeline.audio_enhancer] 
Initialized microVAD

2025-04-03 12:10:13.675 DEBUG (MainThread) [custom_components.stream_assist.core] 
run_assist error <class 'TypeError'>: PipelineInput.__init__() got an unexpected keyword argument 'conversation_id'

2025-04-03 12:10:13.675 DEBUG (MainThread) [homeassistant.components.assist_pipeline.audio_enhancer] 
Initialized microVAD

2025-04-03 12:10:13.675 DEBUG (MainThread) [custom_components.stream_assist.core] 
run_assist error <class 'TypeError'>: PipelineInput.__init__() got an unexpected keyword argument 'conversation_id'

2025-04-03 12:10:13.675 DEBUG (MainThread) [homeassistant.components.assist_pipeline.audio_enhancer] 
Initialized microVAD
```

**Comment by vivobg** [comment]
I had the same issue with memory filling up within seconds when i upgraded HA to 2025.4.1.
Related issue: https://github.com/AlexxIT/StreamAssist/issues/63

**Comment by justicefreed** [comment]
For what it's worth, I had the same issue - had reboot loops until I disabled the Stream Assist integration.  When trying to re-enable, home assistant would freeze nearly immediately, crashing with an OOM.

For whatever reason, [this fork from vash2695](https://github.com/vash2695/StreamAssistCC/) here seems to work just fine for me without issue, which does make me suspect some relationship with the newer continued conversation features, since that fork has some support for that.

**Comment by Tobi-Wheeler** [comment]
Any idea when this might be fixed please?

**Comment by SzaKiKa1** [comment]
@AlexxIT I hope you can fix it, soon. We are really like your solution, please let us to continue to use this nice integration.

**Comment by AlexxIT** [comment]
I'm working on a different solution right now. It should solve the tasks of this component even better. I don't want to add details until it's ready.

**Comment by Tobi-Wheeler** [comment]
> I'm working on a different solution right now. It should solve the tasks of this component even better. I don't want to add details until it's ready.

So you are saying this integration is done for and we should uninstall it?
Just trying to clarify as I only just got this going on my panel and loved it for 2 weeks before it broke. 
Love being able to use a remote mic stream!

**Comment by AlexxIT** [comment]
I plan to return to this integration after I release a new solution.
Perhaps some of the current users will migrate to the new solution.

**Comment by florian-asche** [comment]
> I plan to return to this integration after I release a new solution. Perhaps some of the current users will migrate to the new solution.

what do you have in mind? I was thinking we have the wyoming-satellite, maybe we can pipe the output to that or something like that? That would require less maintenance...

**Comment by TaeKwonBow** [comment]
> I plan to return to this integration after I release a new solution. Perhaps some of the current users will migrate to the new solution.

Cool, I am looking forward to your new solution and a fix to stream assist. Thank you!

FWIW I and a few others ended up on stream assist from this project which points people to stream assist as one of the options. IT's sort of an Amazon Alexa Show DIY project for home assistant :)

https://github.com/dinki/View-Assist

**Comment by AlexxIT** [comment]
I'm happy to introduce you to something I've been working on lately: https://github.com/AlexxIT/StreamAssist/issues/66

**Comment by Tobi-Wheeler** [comment]
Can we impliment this through frigate?

**Comment by tbrasser** [comment]
> Can we impliment this through frigate?

Yes but frigate needs this newest (not yet released) version of go2rtc first.

And probably you wanna put in HA configuration.yaml:

```yaml
go2rtc:
  url: http://frigate-ip:1984
```

**Comment by Tobi-Wheeler** [comment]
Any idea when the latest go2rtc will be pushed to frigate so we can give it a go?

**Comment by AlexxIT** [comment]
https://docs.frigate.video/configuration/advanced/#custom-go2rtc-version

**Comment by Ehipock** [comment]
Hopefully you can fix it soon! this is actually a must have, such a pity that I just discovered it and its not working, but in your YT video all seems to be as expected and look amazing. Thank you

**Comment by Tobi-Wheeler** [comment]
has anyone actually got this working through go2rtc???? want to give it a try but don't want to mess up my frigate!

**Comment by tbrasser** [comment]
(huh, GH shows some weird comment order, I was replying to @Tobi-Wheeler )

Kinda, but my wall tablets lose their microphone permission every day it seems (android ip webcam), and I didn't get the response working on a different player. Also the  gain and sensitivity numbers I've no idea what to set them to. But updating go2rtc to latest nightly, adding config to frigate config, and then adding them via wyoming integration in HA works perfectly.

**Comment by Tobi-Wheeler** [comment]
> (huh, GH shows some weird comment order, I was replying to [@Tobi-Wheeler](https://github.com/Tobi-Wheeler) )
> 
> Kinda, but my wall tablets lose their microphone permission every day it seems (android ip webcam), and I didn't get the response working on a different player. Also the gain and sensitivity numbers I've no idea what to set them to. But updating go2rtc to latest nightly, adding config to frigate config, and then adding them via wyoming integration in HA works perfectly.

So not really stable and useable then? I'm keen to give it a go but don't want to use dev go2rtc as I will forget I've done it and it wont update automatically anymore once the custom go2rtc is installed. guess ill wait for the new go2rtc to be pushed to frigate or stream assist to be updated.

**Comment by Tobi-Wheeler** [comment]
Hi Alex, just wondering if there has been any progress on a fix for this yet? Cheers

**Comment by GothShoot** [comment]
In core/__init__.py line 164 ...
session=chat_session.async_get_chat_session(
            hass, assist.get("conversation_id")
        ),
instead of passing conversation_id

#69

**Comment by Tobi-Wheeler** [comment]
Does this fix it?Sent from my Galaxy
-------- Original message --------From: Romuald Mocq ***@***.***> Date: 23/07/25  09:50  (GMT+12:00) To: AlexxIT/StreamAssist ***@***.***> Cc: Tobi-Wheeler ***@***.***>, Mention ***@***.***> Subject: Re: [AlexxIT/StreamAssist] Activating the microphone button restarts HomeAssistant (Issue #64) GothShoot left a comment (AlexxIT/StreamAssist#64)
In core/init.py line 164 ...
session=chat_session.async_get_chat_session(
hass, assist.get("conversation_id")
),
instead of passing conversation_id

**Comment by MooCoow** [comment]
Hi just wondering if there have been any updates on fixing this issue? Thank you

**Comment by Alex10011977** [comment]
I would like to know if there is a way to fix this problem?

**Comment by MooCoow** [comment]
Checking in if there have been any progress on fixing this issue or if a workaround has been found. Thank you

**Comment by AlexxIT** [comment]
I haven't had time to address this issue yet. I've heavily reworked the component's logic to align with newer versions of HA, but haven't had a chance to debug it.

**Comment by MooCoow** [comment]
Thank you for the update and your hard work!

**Comment by moskovskiy82** [comment]
Same here. Enabling mic bumps CPU usage over the top and hangs HA 2026.02

**Comment by tbrasser** [comment]
Maybe an alternative for (wall) tablet assist: https://github.com/jxlarrea/voice-satellite-card-integration

for ip cam or other assist sources also go2rtc itself has wyoming module.

**Comment by MooCoow** [comment]
Hi @AlexxIT - I'm still hopeful for a fix for this great custom component you've made. Any updates would be greatly appreciated. Thank you.

**Comment by florian-asche** [comment]
I am currently working on LVA (Linux-Voice-Assistant) @AlexxIT do you see any chances that we can connect it (go2rtc) by audio input/output?

**Comment by AlexxIT** [comment]
I don't have time to follow everything that's happening in the world of IoT. The fast evolution of Home Assistant often breaks many of my components, and they all require attention and fixes.

**Comment by tbrasser** [comment]
Would you recommend stop trying to use streamassist in favor of go2rtc+wyoming?

**Comment by florian-asche** [comment]
> I don't have time to follow everything that's happening in the world of IoT. The fast evolution of Home Assistant often breaks many of my components, and they all require attention and fixes.

do you think it is possible to pipe the audio output to a soundcard input, something like that?

**Comment by AlexxIT** [comment]
> do you think it is possible to pipe the audio output to a soundcard input, something like that?

If I understand your question correctly, the go2rtc module does exactly that.
It can use ALSA for both input (microphone) and output (speaker).
There is direct integration of alsa within go2rtc. And also ffmpeg/ffplay or any other software.

https://github.com/AlexxIT/go2rtc/blob/master/internal/wyoming/README.md

**Comment by AlexxIT** [comment]
> Would you recommend stop trying to use streamassist in favor of go2rtc+wyoming?

It doesn't work well enough yet. I didn't even add a link to it from the main documentation.
I don't plan to abandon this project yet. But I don't have any free time to make changes to it.
I currently have about two dozen projects. And they all require attention.

**Comment by tbrasser** [comment]
> > Would you recommend stop trying to use streamassist in favor of go2rtc+wyoming?
> 
> It doesn't work well enough yet. I didn't even add a link to it from the main documentation.
> I don't plan to abandon this project yet. But I don't have any free time to make changes to it.
> I currently have about two dozen projects. And they all require attention.

Understand completely (which is why I was thinking it might be favorable to focus (according to your own planning of course) on go2rtc instead of on streamAssist.)

Thanks for all of it!

**Comment by florian-asche** [comment]
> > do you think it is possible to pipe the audio output to a soundcard input, something like that?
> 
> If I understand your question correctly, the go2rtc module does exactly that. It can use ALSA for both input (microphone) and output (speaker). There is direct integration of alsa within go2rtc. And also ffmpeg/ffplay or any other software.
> 
> https://github.com/AlexxIT/go2rtc/blob/master/internal/wyoming/README.md

if you find the time to help me and make a example config in docker-compose then i could add the Linux-Voice-Assistant, the wyoming-satellite replacement. I make a container with pipewire-server and linux-voice-assistant, make a custom directory with the socket to the pipewire, add that in a go2rtc container where it can connect to that.

**Comment by MooCoow** [comment]
Just thinking about how wonderful @AlexxIT 's StreamAssist was until upgrading HA to anything after 2025.3

Anyone find an alternative? Thanks.

**Comment by danielholm** [comment]
> Just thinking about how wonderful [@AlexxIT](https://github.com/AlexxIT) 's StreamAssist was until upgrading HA to anything after 2025.3
> 
> Anyone find an alternative? Thanks.

Depending on what you used it for, but View Assist has its own conpanion app now. Also Voice Satellite card is pretty cool too.

**Comment by MooCoow** [comment]
> > Just thinking about how wonderful [@AlexxIT](https://github.com/AlexxIT) 's StreamAssist was until upgrading HA to anything after 2025.3
> > Anyone find an alternative? Thanks.
> 
> Depending on what you used it for, but View Assist has its own conpanion app now. Also Voice Satellite card is pretty cool too.

I really appreciate the suggestions but I need something that will let me transcribe a camera's audio stream into text that I can trigger automations from without the use of a wakeword. 

I was using Stream Assist to listen for keywords spoken to my doorbell camera that would trigger various responses depending on a keyword spoken in a sentence. I would trigger the STT intent pipeline from a motion sensor. A person would walk up to my door, a motion sensor would trigger an audio file of my voice played on a speaker asking the visitor a question. The STT would start listening for several different keywords spoken in a sentence to the doorbell camera. If a keyword matched, a specific audio file would be played back relating to that keyword. It worked brilliantly with solicitors, religious people, or political surveyors coming to my home uninvited. 
Stream Assist was the glue that made this all work perfectly before the HA update.
